#include <iostream>
#include <string>

using std::cout;
using std::cin;
using std::endl;
using std::string;

int main()
{

	//This is the original code from the GitHub Copilot
	//garbage autogenerated by GitHub Copilot!
	//All 30-ish lines below!
	string time = "night";
	string weather = "rainy"; //change this to "rainy" in a minute
	int speed = 60;

	if (time == "night" && weather == "rainy")
	{
		speed = speed - 5; //slow down (more risky driving conditions) 
	}
	else if (time == "night" && weather == "clear")
	{
		speed = speed - 10; //slow down (more risky driving conditions) 
	}
	else if (time == "day" && weather == "rainy")
	{
		speed = speed - 10; //slow down (more risky driving conditions) 
	}
	else if (time == "day" && weather == "clear")
	{
		speed = speed - 15; //slow down (more risky driving conditions) 
	}
	else
	{
		cout << "Continuing to drive at current speed" << endl;
	}

	cout << "Final speed " << speed << endl;
	return 0;
}